### ISSUE TITLE
Nette 2.4 $template->translate($vars) is deprecated

### ISSUE THREAD

**Issue by JanGalek** [Kdyby/Translation#112]
Nette 2.4 return this message,
`Invoking filters via $template->translate($vars) is deprecated, use ($vars|translate)`

**Comment by enumag** [comment]
There already are two pull requests targeting this issue.

**Comment by simPod** [comment]
Have you solved it? I temporarily forked latte/latte and disabled the message

**Comment by tomaj** [comment]
Same here

**Comment by hlavacz** [comment]
Waiting.... :)

**Comment by JanGalek** [comment]
I forked it with fix ;)
https://github.com/JanGalek/Translation/commit/7f3e9e6f9c4493af51573f8ab8d1c6558b47d6a6

**Comment by fprochazka** [comment]
Solved with https://github.com/Kdyby/Translation/commit/8c9aa8174610b8c05523d96d2a8bda0731a1e62f, thank you!

**Comment by zapotocnylubos** [comment]
when i install clear sandbox and require kdyby\translation, i still have this problem.
**Invoking filters via $template->translate($vars) is deprecated, use ($vars|translate)**

**Comment by chlustanec** [comment]
Same here. I have newest nette, newest kdyby/translation, both installed by composer, but the "Invoking filters via $template->translate($vars) is deprecated, use ($vars|translate)" message is still showing

**Comment by FilipLukac** [comment]
mee too, same error

**Comment by chlustanec** [comment]
I have found out, that this message is thrown only if {_string} is in foreach loop (probably other loops too, but i haven't tested. When used outside of loop, translation work perfectly.

**Comment by FilipLukac** [comment]
For me, this error is throwed in every latte tempalte using {_string}

**Comment by FilipLukac** [comment]
@chlustanec when I required `dev-master` everything is working

**Comment by miloshavlicek** [comment]
Please tag new version with this issue solved.

**Comment by FilipLukac** [comment]
@miloshavlicek - sounds like a good idea ;) @fprochazka

**Comment by landsman** [comment]
ping :)

**Comment by FilipLukac** [comment]
same here #129

**Comment by mario-cizmarik** [comment]
the same

**Comment by martinjinda** [comment]
I've tried `dev-master` but still, I got the same error.

**Comment by jvitasek** [comment]
@martinjinda Had the same problem, needed to delete temp files, now everything's OK.

**Comment by zvitek** [comment]
@fprochazka it's possible to create a new version with this issue? Unfortunately this commit 8c9aa81 is not in `master` neither `dev-master`. Thx
